name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc-15, clang-20]

    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }}
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
