name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm64' || 'ubuntu-latest' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        compiler: [clang, gcc]
        sanitizer-config:
          - name: addrsan
            enable-flags: "--enable-asan --enable-lsan --enable-ubsan"
            build-type: "addrsan"
          - name: threadsan
            enable-flags: "--enable-tsan"
            build-type: "threadsan"

    container: ghcr.io/mlv-wip/${{ matrix.compiler }}-builder:latest

    steps:
    - uses: actions/checkout@v4
    - name: configure (${{ matrix.sanitizer-config.name }})
      run: ./configure ${{ matrix.sanitizer-config.enable-flags }} --enable-tests --enable-demo --build-type=${{ matrix.sanitizer-config.build-type }}
    - name: make
      run: make
    - name: make test
      run: make test
