name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-with-clang:
    runs-on: ubuntu-latest
    container: ghcr.io/mlv-wip/clang-builder:latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test

  build-with-gcc:
    runs-on: ubuntu-latest
    container: ghcr.io/mlv-wip/gcc-builder:latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
